### ISSUE TITLE
Switch event triggering to trigger on Amps instead of ADC bins

### ISSUE THREAD

**Issue by slwatkins** [spice-herald/pytesdaq#18]
The continuous triggering algorithm currently builds PSDs and triggers in units of ADC bins. However, the conversion to Amperes is nonlinear (ADC to volts is a polynomial conversion). Thus, to make sure we use the same exact template and PSD in both the triggering and the feature extraction, the triggering algorithm should use traces converted from ADC bins to Amperes.

**Comment by slwatkins** [comment]
@serfass can this be closed now?

**Comment by serfass** [comment]
Fixed in release 0.2.5
