### ISSUE TITLE
We have two nested functions for merging triggers

### ISSUE THREAD

**Issue by slwatkins** [spice-herald/pytesdaq#22]
I've noticed that both the `OptimumFilt` class and the `ContinuousData` classes in `pytesdaq/processing/trigger.py` both have different methods of merging triggers within some window. I believe the current setup means that triggers are merged that are within half a trace length first, which is set by `OptimumFilt`, and then `ContinuousData` checks the merge windows again based on whatever the setting was.

https://github.com/spice-herald/pytesdaq/blob/120aeb4e30706d88cc0d31a2dc44a4812f4fcdc9/pytesdaq/processing/trigger.py#L170-L172

https://github.com/spice-herald/pytesdaq/blob/120aeb4e30706d88cc0d31a2dc44a4812f4fcdc9/pytesdaq/processing/trigger.py#L877-L878

Should we just remove the trigger merging in `OptimumFilt`? Seems like the easiest solution. @serfass?

**Comment by slwatkins** [comment]
@serfass can this be closed now with the latest merges?

**Comment by serfass** [comment]
Keeping only pileup merging within OptimumFilt class for now
